---
title: "Report"
author: "Stephen Kelly"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    css: report_styles.css 
    keep_md: yes
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
# Tabbed Sections {.tabset .tabset-fade .tabset-pills}
library("knitr")
library("yaml")

knitr::opts_chunk$set(echo = FALSE)

# load external config file
report_config <- yaml.load_file('report_config.yml')

# get a copy of the global environment
report_global_env <- as.environment(1)

# ~~~~~ FUNCTIONS ~~~~~ # 
tsprintf <- function(fmt, ...){
    # print a formatted message with timestamp
    m <- sprintf(fmt, ...)
    # message(sprintf('[%s] %s', format(Sys.time(), "%H:%M:%S"), m))
    m <- sprintf('[%s] %s', format(Sys.time(), "%H:%M:%S"), m)
    return(m)
}

# ~~~~~ FUNCTIONS ~~~~~ #
knit_isolated_child <- function(input, parent_env, ...) {
    # knit a child document in an isolated state, only inheriting the passed env
    # this way, we can control which env the children inherit without them getting
    # polluted with each others' envs (default action)
    evaluationEnv <- list2env(x = list(...), parent = parent_env)
    cat(asis_output(knit_child(input = input, envir = evaluationEnv, quiet = TRUE)))
    # return(evaluationEnv)
}

```

```{r find_child_docs, eval=FALSE}

# search the current directory recursively to find all available child docs
# maybe dont do this since its super slow and less reliable

# search for child report documents to add to this report
all_child_docs <- dir(pattern = '*_report.Rmd$', full.names = TRUE, recursive = TRUE)

# find any items in the excluded dirs
remove_childs <- c()
for(i in seq_along(all_child_docs)){
    ichild <- all_child_docs[i]
    
    for(q in seq_along(report_config[["report_exclude_dirs"]])){
        qpattern <- report_config[["report_exclude_dirs"]][q]
        
        # check if patter matches any dirnames
        if(grepl(pattern = qpattern, x = dirname(ichild))){
            remove_child <- grep(pattern = qpattern, x = dirname(ichild), value = TRUE)
            remove_childs <- c(remove_childs, remove_child)
        }
    }
}

# remove items found to be in excluded dirs
if(! is.null(remove_childs)) all_child_docs <- all_child_docs[which(! all_child_docs %in% remove_childs)]

# empty vectors to hold expected vs. unexpected found docs
known_child_docs <- c()
unknown_child_docs <- c()

for(i in seq_along(all_child_docs)){
    ichild <- all_child_docs[i]
    
    # if the discovered child doc is listed in the config
    if(basename(ichild) %in% names(report_config[["report_input_dirs"]])){
        known_child_docs <- c(known_child_docs, ichild)
    } else {
        unknown_child_docs <- c(unknown_child_docs, ichild)
    }
}

```

```{r, find_knit_known_child_docs, results='asis'}

# only search for the known child docs instead

# empty vectors to hold expected vs. unexpected found docs
known_child_docs <- c()
unknown_child_docs <- c()

# look in the dirs where we expect to find child reports as set by the configs
for(i in seq_along(report_config[["report_input_dirs"]])){
    report_input_dir <- report_config[["report_input_dirs"]][[i]]
    report_file <- names(report_config[["report_input_dirs"]])[i]

    report_path <- normalizePath(file.path(report_input_dir, report_file))
    
    # cat(tsprintf('[%s] %s %s %s\n', getwd(), report_input_dir, report_file, report_path), file = "mesages.txt", append = TRUE)

    # check if the expected dir exists
    if(dir.exists(report_input_dir)){
        # check if the report file exists
        if(file.exists(report_path)){
            # known_child_docs <- c(known_child_docs, report_path)
            knit_isolated_child(input = report_path, parent_env = report_global_env, input_dir = report_input_dir)
        }
    }
}
# cat(tsprintf('%s\n', known_child_docs), file = "mesages.txt", append = TRUE)
```

```{r knit_known_children, eval=FALSE, results='asis'}


# something is screwed up here ditch this !! 
# there is something broken in the loop, it only makes one iteration then dies halfway through the second



# if a child doc is in the report config, pass it special params when compiling


# get_input_dir <- function(report_name, report_config){
#     # get the matching input dir for a report from the config
#     input_dir <- report_config[["report_input_dirs"]][[report_name]]
#     return(input_dir)
# }



# ~~~~~ RUN ~~~~~ #
# include known child docs, in the order listed in the config
cat(tsprintf('Knitting child docs...\n'), file = "mesages.txt", append = TRUE)
for(i in seq(length(report_config[["report_input_dirs"]]))){
    # known report data from configs
    report_name <- names(report_config[["report_input_dirs"]])[i]
    input_dir <- report_config[["report_input_dirs"]][[i]]
    
    cat(tsprintf('Now processing: %s %s\n', report_name, input_dir), file = "mesages.txt", append = TRUE)
    cat(tsprintf('is.null(known_child_docs): %s \n', is.null(known_child_docs)), file = "mesages.txt", append = TRUE)
    
    # skip if no known reports were found
    if(is.null(known_child_docs)){
        cat(tsprintf('no items left in known_child_docs: %s\n', known_child_docs), file = "mesages.txt", append = TRUE)
        break()
    }
    
    # find matching discovered known reports
    cat(tsprintf('known_child_docs %s \n', known_child_docs), file = "mesages.txt", append = TRUE)
    cat(tsprintf('basename(known_child_docs) %s \n', basename(known_child_docs)), file = "mesages.txt", append = TRUE)
    if(report_name %in% basename(known_child_docs)){
        known_child_doc <- known_child_docs[which(basename(known_child_docs) == report_name)]
        
        # knit it
        cat(tsprintf('Knitting: %s\n', known_child_doc), file = "mesages.txt", append = TRUE)
        knit_isolated_child(input = known_child_doc, parent_env = report_global_env, input_dir = input_dir)
        
        # remove it from the vector of discovered reports
        cat(tsprintf('known_child_docs[ ! which(basename(known_child_docs) == report_name)]: %s\n', known_child_docs[ ! which(basename(known_child_docs) == report_name)]), file = "mesages.txt", append = TRUE)
        cat(tsprintf('known_child_docs[ which(basename(known_child_docs) == report_name)]: %s\n', known_child_docs[ ! which(basename(known_child_docs) == report_name)]), file = "mesages.txt", append = TRUE)
        
        known_child_docs <- known_child_docs[ ! which(basename(known_child_docs) == report_name)]
    }
}

# include each discovered known child doc in the order they were found (maybe not a good idea)
# for(i in seq_along(known_child_docs)){
#     ikchild <- known_child_docs[i]
#     message(ikchild)
#     input_dir <- get_input_dir(report_name = basename(known_child_docs[1]), report_config = report_config)
#     message(input_dir)
#     knit_isolated_child(input = ikchild, parent_env = report_global_env, input_dir = input_dir)
# }


# this is the code chunk for knitting unkown child docs; dont do it
# ```{r, child = unknown_child_docs}
# ``` 
```


# System Information 

```{r}
# {.tabset .tabset-pills}
# cat(tsprintf('printing system info \n'), file = "mesages.txt", append = TRUE)
## Hide

## Show
# system info
cat(sprintf("System:\n%s\n%s", system("hostname", intern = TRUE), system("uname -srv", intern = TRUE)))
cat(sprintf("System user:\n%s", system("whoami", intern = TRUE)))
# dir
cat(sprintf("System location:\n%s", system('pwd',intern=T)))

# repo info
cat(sprintf("Git Remote:\n%s\n", system('git remote -v',intern=T)))
cat(sprintf("Git branch and commit\n%s", system('printf "%s: %s" "$(git rev-parse --abbrev-ref HEAD)" "$(git rev-parse HEAD)"',intern=T)))

# date time
cat(sprintf("Time and Date of report creation:\n%s", system("date", intern = TRUE)))

# R system info, packages, etc
sessionInfo()

# save current session
save.image(file="final_report_data.Rdata",compress = TRUE)
```
