---
output: 
  html_document: 
    keep_md: yes
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
params:
  input_dir: .
---
<!-- Report with sample table and read mapping info -->
```{r report_summary_setup, include=FALSE}
library("knitr")
library("yaml")
library("tools")
library("data.table")
library("reshape2")
library("ggplot2")

# ~~~~~ FUNCTIONS ~~~~~ #
get_firstline <- function(my_file){
    if(length(readLines(my_file)) >= 1){
        file_contents <- readLines(my_file)[1]
    } else {
        file_contents <- NA
    }
    return(file_contents)
}


# ~~~~~ PARAMS ~~~~~ # 
report_config <- yaml.load_file("report_config.yml")

analysis_ID_file <- tools::file_path_as_absolute(report_config[["analysis_id_file"]])
results_ID_file <- tools::file_path_as_absolute(report_config[["results_id_file"]])
samples_fastq_raw_file <- tools::file_path_as_absolute(report_config[["samples_fastq_raw_file"]])
summary_combined_file <- tools::file_path_as_absolute(report_config[["summary_combined_file"]])
save.image(file = 'load_summary_params.Rdata')

# ~~~~~ LOAD DATA ~~~~~ # 
analysis_ID <- get_firstline(analysis_ID_file)
results_ID <- get_firstline(results_ID_file)

# load the samples table
samples_fastq_df <- read.delim(file = samples_fastq_raw_file, sep = ',', header = FALSE)
colnames(samples_fastq_df) <- c("sample", "R1", "R2")
samples_df <- as.data.frame(unique(as.character(samples_fastq_df[["sample"]])))
colnames(samples_df) <- "sample"

# load the summary combined file
summary_combined_table <- read.delim(file = summary_combined_file, sep = ',')
setnames(x = summary_combined_table, old = c("X.SAMPLE"), new = c("sample"))

```

```{r, mapping_table}
# make the mapping table and plots
mapping_table <- summary_combined_table[, "sample", drop = FALSE]
mapping_table["mapped"] <- summary_combined_table[["MAPPED.READS"]]
mapping_table["deduplicated"] <- summary_combined_table[["DEDUPLICATED.READS"]]

mapping_table <- reshape2::melt(mapping_table,id.vars="sample",variable.name="type",value.name="reads")

mapping_table[["reads"]] <- as.numeric(mapping_table[["reads"]]) / 1e6

mapping_table[["type"]] <- factor(x = mapping_table[["type"]], levels = sort(unique(as.character(mapping_table[["type"]]), decreasing = TRUE)))

mapping_plot <- ggplot(data = mapping_table, aes(x = sample, y = reads, fill = type)) + 
    geom_bar(stat="identity", position = "dodge") + 
    ggtitle("Sample Read Mapping") + 
    coord_flip() + 
    ylab("reads (millions)") + 
    theme_bw() +
    theme(panel.grid.minor = element_blank())
```


# Summary

Analysis ID: __`r as.character(analysis_ID)`__

Results ID: __`r as.character(results_ID)`__

## Samples

```{r print_samples_df, results='asis'}
kable(samples_df, row.names = TRUE, caption = "Samples included in the analysis") # , align = c("c")
# datatable(samples_df, caption = "Samples included in the analysis")
```


## Mapping

```{r print_mapping_plot, fig.height=12, fig.width=8}
print(mapping_plot)
```
